# Generated by Django 3.1.1 on 2020-10-05 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('form_url', models.URLField(blank=True, default='', help_text='links to a form')),
                ('redirect_url', models.URLField(blank=True, default='', help_text='redirect to external page')),
                ('basic_info', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
