# Generated by Django 3.1.1 on 2020-10-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201007_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_date', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(default='', max_length=256)),
                ('action', models.CharField(choices=[('basic_info', 'Basic info'), ('json', 'Json Response'), ('redirect', 'Redirect')], default='basic_info', max_length=16)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.qrcode')),
            ],
        ),
    ]
