# Generated by Django 3.1.1 on 2020-10-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apihit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apihit',
            name='user_agent',
        ),
    ]
