# Generated by Django 3.1.1 on 2020-10-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_apihit_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='form_url',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='redirect_url',
        ),
        migrations.CreateModel(
            name='LinkUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='', help_text='redirect to external page')),
                ('priority', models.FloatField(default=1)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.qrcode')),
            ],
        ),
    ]
