# Generated by Django 3.1.1 on 2020-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201008_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkurl',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of the url. Used in buttons and links when a code is scanned.', max_length=64),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('kiosk', 'Kiosk Mode'), ('redirect', 'Redirect Mode'), ('info_page', 'Information Page Mode')], default='redirect', help_text='\nSets the mode this code is in.\nKiosk Mode: Show buttons to choose a link from\nRedirect Mode: Instantly redirects to the url with the highest priority.\nInformation Page Mode: Show basic info with links to different urls\n', max_length=16),
        ),
    ]
