# Generated by Django 3.1.1 on 2020-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201008_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkurl',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='apihit',
            name='action',
            field=models.CharField(choices=[('html', 'Html'), ('json', 'Json Response'), ('redirect', 'Redirect')], default='html', max_length=16),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mode',
            field=models.CharField(choices=[('kiosk', 'Kiosk Mode'), ('redirect', 'Redirect Mode'), ('info_page', 'Information Page Mode')], default='redirect', help_text='\nSets the mode this code is in.<br/>\nKiosk Mode: Show buttons to choose a link from<br/>\nRedirect Mode: Instantly redirects to the url with the highest priority.<br/>\nInformation Page Mode: Show basic info with links to different urls\n', max_length=16),
        ),
    ]
