# Generated by Django 3.1.3 on 2020-12-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201202_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apihit',
            options={'ordering': ['-hit_date']},
        ),
        migrations.AlterField(
            model_name='apihit',
            name='action',
            field=models.CharField(choices=[('basic_info', 'Basic Info'), ('kiosk', 'Kiosk'), ('json', 'Json Response'), ('redirect', 'Redirect'), ('error', 'Error')], default='basic_info', max_length=16),
        ),
        migrations.AlterField(
            model_name='apihit',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.qrcode'),
        ),
    ]
