# Generated by Django 3.1.3 on 2020-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201203_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='apihit',
            name='message',
            field=models.CharField(blank=True, help_text='Extra information about errors or other extra info', max_length=255, null=True),
        ),
    ]
