# Generated by Django 3.1.3 on 2020-12-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_apihit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='api.department'),
        ),
    ]
