# Generated by Django 3.1.3 on 2020-12-15 15:27

from django.db import migrations, models
import uuid
from api.models import QRCode


def update_qrcodes(*args, **kwargs):
    codes = QRCode.objects.all()
    for code in codes:
        matches = QRCode.objects.filter(title=code.title).count()
        print(matches)
        if matches > 1:
            code.title += str(uuid.uuid4())[:5]
        code.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_auto_20201209_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='short_uuid',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(update_qrcodes),
        migrations.AlterField(
            model_name='qrcode',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
