# Generated by Django 3.1.3 on 2020-12-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201215_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='short_uuid',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
